ndk

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,20 +1,20 @@
 ngx_addon_name=ngx_http_set_misc_module
 
-#if test -n "$ngx_module_link"; then
-#    if test -n "$NDK_SRCS"; then
-#        echo "found ngx_devel_kit for ngx_set_misc; looks good."
-#    else
-#        echo "error: ngx_devel_kit is required to build ngx_set_misc; please put it before ngx_set_misc." 1>&2
-#        exit 1
-#    fi
-#else
-#    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
-#        echo "found ngx_devel_kit for ngx_set_misc; looks good."
-#    else
-#        echo "error: ngx_devel_kit is required to build ngx_set_misc; please put it before ngx_set_misc." 1>&2
-#        exit 1
-#    fi
-#fi
+if test -n "$ngx_module_link"; then
+    if test -n "$NDK_SRCS"; then
+        echo "found ngx_devel_kit for ngx_set_misc; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_set_misc; please put it before ngx_set_misc." 1>&2
+        exit 1
+    fi
+else
+    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+        echo "found ngx_devel_kit for ngx_set_misc; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_set_misc; please put it before ngx_set_misc." 1>&2
+        exit 1
+    fi
+fi
 
 SET_MISC_SRCS="                                                             \
             $ngx_addon_dir/src/ngx_http_set_base32.c                        \
@@ -33,7 +33,6 @@ SET_MISC_SRCS="                                                             \
             $ngx_addon_dir/src/ngx_http_set_random.c                        \
             $ngx_addon_dir/src/ngx_http_set_secure_random.c                 \
             $ngx_addon_dir/src/ngx_http_set_rotate.c
-                    $ngx_addon_dir/src/ndk_upstream_list.c                                \
             "
 
 SET_MISC_DEPS="                                                             \
@@ -53,7 +52,6 @@ SET_MISC_DEPS="                                                             \
             $ngx_addon_dir/src/ngx_http_set_rotate.h                        \
             $ngx_addon_dir/src/ngx_http_set_secure_random.h                 \
             $ngx_addon_dir/src/ngx_http_set_misc_module.h                   \
-                    $ngx_addon_dir/src/ndk_upstream_list.h                                \
             "
 
 if [ $USE_OPENSSL = YES -o $MAIL_SSL = YES ]; then
@@ -61,6 +59,7 @@ if [ $USE_OPENSSL = YES -o $MAIL_SSL = YES ]; then
     SET_MISC_SRCS="$SET_MISC_SRCS $ngx_addon_dir/src/ngx_http_set_hmac.c"
 fi
 
+CFLAGS="$CFLAGS -DNDK_SET_VAR -DNDK_UPSTREAM_LIST"
 USE_SHA1=YES
 USE_MD5=YES
 
